// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub(crate) fn reflens_structure_crate_output_describe_instances_output_next_token(input: &crate::output::DescribeInstancesOutput) -> std::option::Option<& std::string::String> {
                    let input = match &input.next_token {
                        None => return None,
                        Some(t) => t
                    };
Some(input)
                }

pub(crate) fn lens_structure_crate_output_describe_instances_output_reservations(input: crate::output::DescribeInstancesOutput) -> std::option::Option<std::vec::Vec<crate::model::Reservation>> {
                    let input = match input.reservations {
                        None => return None,
                        Some(t) => t
                    };
Some(input)
                }

